remove metrix type and fix workflow step

diff --git a/.github/workflows/functional_tests_common.yml b/.github/workflows/functional_tests_common.yml
--- a/.github/workflows/functional_tests_common.yml
+++ b/.github/workflows/functional_tests_common.yml
@@ -50,9 +50,13 @@ jobs:
         with:
           fetch-depth: 0
 
+      # - name: Set safe directory
+      #   run: |
+      #     git config --global --add safe.directory $PROJECT_ROOT
+      ## The above step is commented out because there is no git cli in the container, and it causes the step to fail. The safe directory is set in the next step with a conditional check.
       - name: Set safe directory
         run: |
-          git config --global --add safe.directory $PROJECT_ROOT
+          command -v git && git config --global --add safe.directory $PROJECT_ROOT || true
 
       - name: Setup Python environment
         run: |
